### PR TITLE
>0.89 compliant - "packaged" - 3rd pump integration - code cleanup - and more...

### PR DESCRIPTION
**Pull request by plmilord**
What's different:
- Now support Home Assistant 0.96 Climate major clean up
- Home Assistant 0.89 and higher compliant
- Hass.io ready (crc8 automatically installed when first used of this custom component on Hass.io)
- Support 3 pumps
- Code cleanup
- 'nb_toggle' attribute implemented (optional)
- 'scan_interval' attribute implemented (optional)
- The custom component will setup even if spa is not online
- Totally resilient to spa disconnections
- 'README.md' revised to list next steps

### CODE REVIEW

**Comment by stringy92** [comment]
@plmilord - I have tried the latest fix but still suffering the same issues as above

When the hot tub is set to Fahrenheit the HA display shows - 38.2
When the hot tub is set to Celsius the HA display shows - 77

**Comment by plmilord** [comment]
Ok I see…

My spa is set to Fahrenheit and my HA is set to Fahrenheit too… (work fine)! But like you, when I switch my spa to Celsius, the display double! I'll give it a look!

**Comment by plmilord** [comment]
Solved in this morning upload! Do not hesitate to test and confirm!

**Comment by stringy92** [comment]
@plmilord Works really nicely! I did get this error however, and it caused my HA to lock up, and unable to access so i had to reboot 

`2020-05-14 13:51:54 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.spa_pump_1 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/spaclient/switch.py", line 67, in async_update
    self._spa.read_all_msg()
  File "/config/custom_components/spaclient/spaclient.py", line 172, in read_all_msg
    while (self.read_msg()):
  File "/config/custom_components/spaclient/spaclient.py", line 150, in read_msg
    length = len_chunk[1]
IndexError: index out of range`

Ive added a Hastebin link, as you can read this easier[https://hastebin.com/eyinisidoz.sql](Hastebin)

**Comment by stringy92** [comment]
Just had similar issue, which caused HA to become unresponsive

`2020-05-14 21:13:55 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.spa_light fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/spaclient/light.py", line 46, in async_update
    self._spa.read_all_msg()
  File "/config/custom_components/spaclient/spaclient.py", line 172, in read_all_msg
    while (self.read_msg()):
  File "/config/custom_components/spaclient/spaclient.py", line 150, in read_msg
    length = len_chunk[1]
IndexError: index out of range`

**Comment by plmilord** [comment]
Weird!? Have update every files in your "spaclient" folder? Be sure to dl all the latest files to go trought that folder name change (SpaClient -to- spaclient). I never had those error msg!?

I also had instabilities with HA in past weeks. Since the last update, everything's seem to be fine for me. But in my case, that was not related to this custom component!

Change your setup to fahrenheit for next days and let me know if that bug come back!

Thanks for you follow-up!

**Comment by plmilord** [comment]
stringy92 , have you gone through your problem?

**Pull request closed without merging**
